export enum ConfigEnum {
  DB = 'DB',
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  PORT = 'PORT',
  DB_ROOT_PASSWORD = 'DB_ROOT_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_SYNCHRONIZE = 'DB_SYNCHRONIZE',
}
