# Use root/example as user/password credentials

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: quntta123456
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8010:8080'
